server:
  servlet:
    context-path: /api

spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

app:
  version: @project.version@
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  google:
    client-id: ${GOOGLE_CLIENT_ID}